name:                food
version:             0.1.0.0
github:              "vynlar/cs362_diet"
license:             BSD3
author:              "Adrian Aleixandre"
maintainer:          "adrian.aleixandre@gmail.com"
copyright:           "2018 Adrian Aleixandre"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/food#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix-glpk
- boxes

library:
  source-dirs: src

executables:
  food-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - food

tests:
  food-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - food
